### ISSUE TITLE
Opendrive Export

### ISSUE THREAD

**Issue by prasuka4** [brifsttar/OpenDRIVE#17]
Hi @brifsttar 
After installing plugin, the fbx and xodr files were imported in Unreal engine. 
Is it possible to edit and export the opendrive file along with fbx/obj file.
Thanks in Advance

**Comment by brifsttar** [comment]
Hi,

I'm not sure I fully understand the request. You want to edit the OpenDRIVE file in Unreal? That's currently not possible, and we don't foresee implementing this feature in the near future.

**Comment by brifsttar** [comment]
> If we import the data in Unreal engine, can we alter road network i.e., adding lanes, vegetation etc. either in xodr or in fbx?

No. But if you're using RoadRunner, that tool is actually made for that exact use case. Unreal isn't made to edit and export objects/scenes. Though it has basic support for that, it's really not its use case.

The goal of the plugin is to offer read access of the OpenDRIVE network straight in Unreal. This allows creating editor features, such as editing landscape or aligning/spawning actors relative to the road network. It can also lead to developing end-user features, for example we use the OpenDRIVE data to actually move actors (e.g., vehicles, pedestrians) at runtime (though this is not open-source).

Editing the network in Unreal would be a dream for many people, but it's a huge undertaking that's way beyond the resources of our open-source plugin. That's also why there are full-feature (expensive) tools on the market that specialize in that exact use case (e.g., RoadRunner, Trian3D). The closest that come to mind straight-in-Unreal is [CityBLD](https://www.worldbld.com/), but as far as I know, they don't have OpenDRIVE support.

**Comment by prasuka4** [comment]
Thank you very much for the repsonse
