### ISSUE TITLE
Model adaptation questions

### ISSUE THREAD

**Issue by JpHoooo** [brifsttar/OpenDRIVE#19]
Hi, brifsttar. Thank you very much for providing such a great plugin.💕

The document mentions using [Der Sky](https://www.unrealengine.com/marketplace/en-US/profile/Der+Sky?count=20&sortBy=effectiveDate&sortDir=DESC&start=0)'s model assets. I would like to know how you solve the problem of adapting the model to the Lane width?

**Comment by brifsttar** [comment]
Hi, I'm happy to learn that you find the plugin useful!

Is your question about creating the actual road geometry based on maybe [this asset](https://www.unrealengine.com/marketplace/en-US/product/road-essentails)? If so, that's not really currently handled by the plugin. On our side we generate both the OpenDRIVE and the geometry using RoadRunner. Generating the actual road geometry in Unreal from OpenDRIVE alone is a bit tricky, it's something that we're not really focusing on, but we're following the works on [CityBLD](https://www.worldbld.com/) to maybe work with it later.

When mentioning DerSky's asset, I was mostly talking about horizontal and vertical signage, not so much the actual road itself (it's a relatively new product from them).
