### ISSUE TITLE
Failed to download

### ISSUE THREAD

**Issue by jampy-sze** [brifsttar/OpenDRIVE#2]
Hi, I cloud not download the whole repo, because the esmini link is broken in the /Source/ThirdParty/RoadManager/modules/.

**Comment by brifsttar** [comment]
Hi,

Thanks for the bug report, it should be fixed in https://github.com/brifsttar/OpenDRIVE/commit/0952c4f66cd2562fcc80ffe33c019cebc49e4121

Let me know if it now works for you.

**Comment by jampy-sze** [comment]
Hi, Thank you, now it works!
